### ISSUE TITLE
Which one is CUDA runtime version?

### ISSUE THREAD

**Issue by Towhid1** [squat/darkapi#2]
layer     filters    size              input                output
    0 darkapi: ./src/cuda.c:36: check_error: Assertion `0' failed.
CUDA Error: CUDA driver version is insufficient for CUDA runtime version

**Comment by squat** [comment]
Hi @Towhid1 the project is compiled using the `nvidia/cuda:9.1-cudnn7-devel` Docker container (you can find more details in the Makefile). That mean CUDA 9.1 and the CUDA deep neural network library version 7.

**Comment by Towhid1** [comment]
Thank you @squat
